#!/usr/bin/env python3
"""Generate Vivado cache sweeps and summarize cache experiment CSV files."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
DEFAULT_TCL = ROOT / "sim" / "tools" / "cacheflow_sweep.tcl"
DEFAULT_CSV = ROOT / "sim" / "results" / "cache_results_sweep_combined_current.csv"
DEFAULT_REPORT = ROOT / "sim" / "results" / "cacheflow_summary.md"

SINGLE_CONFIGS = [
    ("size_4096", 4096, 32, 2),
    ("size_8192", 8192, 32, 2),
    ("size_16384", 16384, 32, 2),
    ("block_16", 8192, 16, 2),
    ("block_32", 8192, 32, 2),
    ("block_64", 8192, 64, 2),
    ("ways_1", 8192, 32, 1),
    ("ways_2", 8192, 32, 2),
    ("ways_4", 8192, 32, 4),
]

GRID_CONFIGS = [
    (f"grid_b{block}_w{ways}", 8192, block, ways)
    for block in (16, 32, 64)
    for ways in (1, 2, 4)
]


def resolve_path(path: str, default: Path) -> Path:
    if not path:
        return default
    candidate = Path(path)
    return candidate if candidate.is_absolute() else ROOT / candidate


def selected_configs(mode: str) -> list[tuple[str, int, int, int]]:
    if mode == "single":
        return SINGLE_CONFIGS
    if mode == "grid":
        return GRID_CONFIGS
    return SINGLE_CONFIGS + GRID_CONFIGS


def generate_tcl(mode: str, output: Path) -> None:
    configs = selected_configs(mode)
    lines = [
        "# Generated by cacheflow. Source this file in the Vivado Tcl Console.",
        "proc cacheflow_run_config {name size block ways} {",
        "    set simset [get_filesets sim_1]",
        "    catch {close_sim -force}",
        "    set_property top tb_cache_perf $simset",
        "    set_property generic [list RUN_ALL_WORKLOADS=1 USE_CACHE=1 ENABLE_L2=1 \\",
        "        L1_SIZE_BYTES=$size L1_BLOCK_BYTES=$block L1_WAYS=$ways] $simset",
        "    set_property xsim.simulate.runtime all $simset",
        "    update_compile_order -fileset sim_1",
        '    puts "CACHEFLOW_BEGIN name=$name size=$size block=$block ways=$ways"',
        "    launch_simulation -simset sim_1 -mode behavioral",
        "    run all",
        '    puts "CACHEFLOW_END name=$name"',
        "}",
        "",
        "proc cacheflow_run_all {} {",
    ]
    for name, size, block, ways in configs:
        lines.append(f"    cacheflow_run_config {name} {size} {block} {ways}")
    lines.extend(["}", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(configs)} configurations: {output}")


def number(row: dict[str, str], key: str, default: float = 0.0) -> float:
    try:
        return float(row.get(key, default))
    except (TypeError, ValueError):
        return default


def workload_name(row: dict[str, str]) -> str:
    if row.get("workload"):
        return row["workload"]
    return Path(row.get("program", "unknown")).stem.removeprefix("program_")


def format_value(value: float, digits: int = 2) -> str:
    return f"{value:.{digits}f}"


def summarize_csv(source: Path, output: Path) -> None:
    with source.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    valid_rows = [row for row in rows if row.get("pass", "1") == "1" and row.get("cycles")]
    if not valid_rows:
        raise SystemExit(f"No passing experiment rows found in {source}")

    by_workload: dict[str, list[dict[str, str]]] = defaultdict(list)
    by_config: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in valid_rows:
        by_workload[workload_name(row)].append(row)
        by_config[row.get("config", "unknown")].append(row)

    lines = [
        "# Cacheflow experiment summary",
        "",
        f"- Source: `{source.name}`",
        f"- Passing rows: {len(valid_rows)}/{len(rows)}",
        "",
        "## Best configuration per workload",
        "",
        "| Workload | Best config | Cycles | Speedup | D-Cache hit | L2 hit |",
        "| --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for workload in sorted(by_workload):
        best = min(by_workload[workload], key=lambda row: number(row, "cycles", float("inf")))
        lines.append(
            f"| {workload} | {best.get('config', 'unknown')} | {int(number(best, 'cycles'))} | "
            f"{format_value(number(best, 'speedup_vs_nocache'))}x | "
            f"{format_value(number(best, 'dhitrate'))}% | "
            f"{format_value(number(best, 'l2hitrate'))}% |"
        )

    lines.extend(
        [
            "",
            "## Configuration averages",
            "",
            "| Config | Runs | Average cycles | Average speedup | Average D-Cache hit |",
            "| --- | ---: | ---: | ---: | ---: |",
        ]
    )
    for config in sorted(by_config):
        group = by_config[config]
        count = len(group)
        avg_cycles = sum(number(row, "cycles") for row in group) / count
        avg_speedup = sum(number(row, "speedup_vs_nocache") for row in group) / count
        avg_dhit = sum(number(row, "dhitrate") for row in group) / count
        lines.append(
            f"| {config} | {count} | {avg_cycles:.0f} | "
            f"{format_value(avg_speedup)}x | {format_value(avg_dhit)}% |"
        )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Summarized {len(valid_rows)} passing rows: {output}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    generate = subparsers.add_parser("generate", help="Generate a Vivado Tcl parameter sweep.")
    generate.add_argument("--mode", choices=("single", "grid", "all"), default="all")
    generate.add_argument("--output", default="", help="Output path relative to project root.")

    summarize = subparsers.add_parser("summarize", help="Summarize a cache experiment CSV.")
    summarize.add_argument("--input", default="", help="CSV path relative to project root.")
    summarize.add_argument("--output", default="", help="Markdown output relative to project root.")

    args = parser.parse_args()
    if args.command == "generate":
        generate_tcl(args.mode, resolve_path(args.output, DEFAULT_TCL))
    else:
        summarize_csv(
            resolve_path(args.input, DEFAULT_CSV),
            resolve_path(args.output, DEFAULT_REPORT),
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
